name: update cff

on:
  push:
    branches:
      - main

jobs:
  update-cff:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: btraven00/cffbump@v1
        with:
          git-min-commits: '1'
          include-sources: 'git,crossref'
          doi: '10.1371/journal.pone.0021373'
